### ISSUE TITLE
Feature request: Update source from destination on PR creation

### ISSUE THREAD

**Issue by JakeBooher** [chinthakagodawita/autoupdate#177]
Currently updates to PR sources only happen when a new commit is made on the destination. However, a PR can be created on destination branch while the source is already outdated and the update will not be triggered

**Comment by chinthakagodawita** [comment]
Hey @JakeBooher - have you tried adding an `on: pull_request` trigger to your workflow? That _may_ resolve your issue.

i.e. instead of:
```yaml
name: autoupdate
on:
  push: {}
jobs:
  autoupdate:
    # [..]
```

You do:
```yaml
name: autoupdate
on: [push, pull_request]
jobs:
  autoupdate:
    # [..]
```

See these docs for more info:
- https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
- https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on

Let me know if that works for you!
