### ISSUE TITLE
autoupdate failing with 404 not found

### ISSUE THREAD

**Issue by JakeBooher** [chinthakagodawita/autoupdate#205]
```
Handling push event on ref 'refs/heads/develop'
PR-30
  Evaluating pull request #30...
  Error: Not Found
```

PR 30 does, in fact, exist so not sure what exactly is going on here internally. Using latest version. The PR is from a fork

This is my workflow yaml:

```yaml
name: autoupdate
on:
  push:
    branches:
      - develop

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1.5.0
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
```
