### ISSUE TITLE
PR not found after initially being monitored

### ISSUE THREAD

**Issue by alfonsoar** [chinthakagodawita/autoupdate#230]
## Background 

Hi @chinthakagodawita, thanks for putting this plugin together!

We found a potential bug that is hopefully an easy fix? 

## Current Behavior 

When a PR is originally being monitored and later gets put into "draft" mode the plugin fails with the error: 

![Screen Shot 2021-09-16 at 1 51 22 PM](https://user-images.githubusercontent.com/22054505/133660757-9c6cde2c-dcc0-44b5-99d2-ff5d7e1755ac.png)

## Expected Behavior 

When a PR is being tracked and then set to "draft" mode the plugin does not fail. 

### Appendix 

Config 
```yaml
name: autoupdate
on:
  push: {} # triggers on all pushes to all branches
jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-20.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          PR_READY_STATE: 'ready_for_review'
          RETRY_COUNT: '1'
          MERGE_CONFLICT_ACTION: 'fail'
```
