### ISSUE TITLE
Unable to resolve actions. Repository not found

### ISSUE THREAD

**Issue by xenjke** [chinthakagodawita/autoupdate#278]
Hello there

Just today when running Actions our merges to master started to fail with:

```
Getting action download info
Error: Unable to resolve actions. Repository not found : chinthakagodawita/autoupdate-action.
```

The workflow:

```yaml
name: "Push Master Automations"
on:
  push:
    branches:
      - master
jobs:
  autoupdate-open-prs:
    name: autoupdate
    runs-on: ubuntu-18.04
    steps:
      - uses: chinthakagodawita/autoupdate-action@699da47083dddb66e5f5d2d48825b2e375a1d6c3
        env:
          GITHUB_TOKEN: "${{ secrets.BOT_GITHUB_TOKEN }}"
```

I'm currently investigating if updating helps or if removing the SHA from `uses` might have something to do with the repository rename and subsecuent redirect, but cloning the repo seems to be working fine locally.
