### ISSUE TITLE
PRs open by dependabot don't get updated

### ISSUE THREAD

**Issue by khavishbhundoo** [chinthakagodawita/autoupdate#333]
If there are open PRs by dependabot in the repo, those PRs will not get updated by autoupdate when a PR is merged into main. 

```
name: autoupdate
on:
  push:
    branches:
      - master

permissions:
  pull-requests: write

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_CONFLICT_ACTION: "ignore"
``` 
Error: Caught error trying to compare base with head: Resource not accessible by integration.

I had to add the following to get detailed error above , otherwise it would just give me a plain `Resource not accessible by integration.` error

Branch protection is disabled and default permission is read/write

```
permissions:
  pull-requests: write
```

Resource not accessible by integration.

**Comment by kevinrobayna** [comment]
This is sadly expected behaviour, “bots” don’t trigger GHA builds. If you wanted to use this action you would need to use a user token rather than GH default one

**Comment by kevinrobayna** [comment]
See this https://github.com/chinthakagodawita/autoupdate#limitations

**Comment by ReenigneArcher** [comment]
Probably better to rebase dependabot PRs.

This is how I handle it.
```yml
  dependabot-rebase:
    name: Dependabot Rebase
    if: >-
      startsWith(github.repository, '<your user or org name>/') &&
      contains(github.event.pull_request.labels.*.name, 'autoupdate_ignore') == false  # a label you want to skip
    runs-on: ubuntu-latest
    steps:
      - name: rebase
        uses: "bbeesley/gha-auto-dependabot-rebase@v1.2.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
```
