### ISSUE TITLE
Schedule event only targetting PR's on main branch

### ISSUE THREAD

**Issue by andynicklen** [chinthakagodawita/autoupdate#356]
Hi,

When using the **schedule** event as the workflow trigger, should it target all PR's, or only PR's on the main branch? As you can see below it's only targeting develop (our main branch). 

![image](https://user-images.githubusercontent.com/28435773/208853580-c5af3b7e-962d-4fe3-be66-c07e2d64c0e3.png)

Here's my workflow:

```
name: auto-update
run-name: auto-update (${{github.event.schedule}})

on:
  schedule:
    - cron: '39 * * * 1-5' # every weekday hour
    - cron: '5 6 * * 1-5' # every weekday

jobs:
  autoupdate:
    name: auto-update
    runs-on: ubuntu-18.04
    steps:
      - name: auto-update-1h
        if: github.event.schedule == '39 * * * 1-5'
        uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          DRY_RUN: 'false'
          PR_FILTER: 'labelled'
          PR_LABELS: 'auto_update_1h'
          MERGE_MSG: 'auto-update from base'
          RETRY_COUNT: '5'
          RETRY_SLEEP: '300'
          MERGE_CONFLICT_ACTION: 'ignore'
      - name: auto-update-1d
        if: github.event.schedule == '5 6 * * 1-5'
        uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          DRY_RUN: 'false'
          PR_FILTER: 'labelled'
          PR_LABELS: 'auto_update_1d'
          MERGE_MSG: 'auto-update from base'
          RETRY_COUNT: '5'
          RETRY_SLEEP: '300'
          MERGE_CONFLICT_ACTION: 'ignore'
```

Thanks
