### ISSUE TITLE
Getting builds to run when action triggered on a PR?

### ISSUE THREAD

**Issue by takanuva15** [chinthakagodawita/autoupdate#399]
Hi, I saw in the README it says "Branch updates events caused by this action will not trigger any subsequent workflows". This is problematic because we need our unit tests to rerun on a PR whenever any new commit or update is pushed to that PR.

Is there any workaround so that normal builds run after the PR executes its action?

**Comment by techgaun** [comment]
@takanuva15 you can use personal access token as a workaround. not ideal but if you create machine user and put proper controls, its a fine workaround until there's a native support for this.

**Comment by andruhon** [comment]
I somewhat worked this around with adding this into the action I want to run after auto-update
```
on:
  push:
  workflow_run:
    workflows: [ 'autoupdate' ]
    types: [ completed ]
```
It Seems to indeed trigger the build, but it seems to be ran against the commit, without any relation to any branch or PR

![Image](https://github.com/user-attachments/assets/db209536-e12e-47bf-93af-fe66d6ec7d76)
and as a result this action is not reflected in the PR, it keeps waiting for the status to be reported.

The successful action triggered by push, for example, looks a bit different, it has a branch associated
![Image](https://github.com/user-attachments/assets/e800941e-4ba7-4364-a6ba-4e63ed97ffeb)


Any ideas how to make ti associated with a correct branch/PR?

**Comment by andruhon** [comment]
I experimented a little bit more and I achieved this to run the workflow on the correct branch, but somehow the PR ruleset does not see that.

```
name: autoupdate
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          DRY_RUN: "false"
          PR_FILTER: "labelled"
          PR_LABELS: "autoupdate"
          MERGE_MSG: "Branch was auto-updated."
          RETRY_COUNT: "5"
          RETRY_SLEEP: "300"
          MERGE_CONFLICT_ACTION: "fail"
  triggerBuild:
    name: triggerBuild
    needs: autoupdate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - run: pwd
      - run: ls
      - run: gh pr list -l autoupdate
        env:
          GH_TOKEN: ${{ github.token }}
      - run: gh pr list -l autoupdate | cut -f3 | while read line ; do gh workflow run Build --ref $line ; done
        env:
          GH_TOKEN: ${{ github.token }}
```
the public repo with this experiment https://github.com/andruhon/try-autoupdate
