### ISSUE TITLE
Autoupdate is checking changes for base branch instead of target branch

### ISSUE THREAD

**Issue by azad-resolver** [chinthakagodawita/autoupdate#402]
I created the rudimentary autoupdate yml file as suggested [here](https://github.com/marketplace/actions/auto-update#usage):
```
name: autoupdate
on:
  # This will trigger on all pushes to all branches.
  push: {}
  # Alternatively, you can only trigger if commits are pushed to certain branches, e.g.:
  # push:
  #   branches:
  #     - master
  #     - unstable
jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-22.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
```

However, it does in fact not update the PR with the latest state of the `target/base` branch (in this case `develop`). The update button is still shown:

<img width="840" alt="image" src="https://github.com/user-attachments/assets/97bbe28b-743c-4384-a22f-a796ab731ab3">

After looking into the log of the autoupdate PR check, I noticed it is wrongfully looking for changes to the _PR branch_ itself (in this case `feature/CA-8408`):

<img width="790" alt="image" src="https://github.com/user-attachments/assets/4ec02e2f-2f1b-4c54-b9b5-8dec10325fed">

I also tried setting `PR_READY_STATE: 'all'` but that led to no change either.

I even tried setting it explicitly to `develop` and `master` but in that case it didn't even show the autoupdate PR check. 
```
push:
    branches:
      - 'develop'
      - 'master'
```      
It really seems to be only checking the branch of the PR itself which makes no sense and differs from the description of the GHA. I assume this must be a bug?

**Comment by azad-resolver** [comment]
Nvm, I was able to fix it by changing it to this:

```
name: autoupdate
on:
  pull_request:
jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-22.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
```

It may be a good idea to clarify this in the documentation, but I believe the fact that it thinks the PR branch is the base/target branch is still a bug.
