### ISSUE TITLE
Permission issues?

### ISSUE THREAD

**Issue by rdegges** [chinthakagodawita/autoupdate#99]
Hey there!

This Github action looks amazing. It'd be sooo useful for a lot of my projects.

I've been trying to get it working on a repo I run, but having some permissions issues that I can't seem to figure out. Here's my config file:

```yaml
name: autoupdate
on:
  push: {}

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

When the action goes to run, however, here's the output I see after looking at the job:

![Screenshot from 2021-01-06 11-54-33](https://user-images.githubusercontent.com/90247/103814107-0054eb80-5016-11eb-94de-e1737f52dc95.png)

Any idea what I need to do to get it working? Also, just as a note, but this action was running on a local pull request for the same repository. Nothing fancy.
